stages:
  - test
  - build
  - release
  - post-release
  - deploy

image: maven:3-jdk-11

test-job:
  stage: test
  script:
    - mvn test

build-job:
  stage: build
  script:
    - mvn clean install

release-job:
  stage: release
  script:
    - mvn package -U
  artifacts:
    paths:
      - target/*.jar

artifact_download:
  stage: post-release
  script:
    - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://gitlab.com/api/v4/projects/44320438/jobs/artifacts/main/download?job=release-job"'

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
